version: 0.2

env:
  variables:
    IMAGE_NAME: flask-ci-app

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo Running tests...
      - pytest
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME $DOCKER_USERNAME/$IMAGE_NAME:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'
